run:
	gcc shell.c -o shell -pthread
	./shell
external:
	gcc mymkdir.c -o mymkdir
	gcc myls.c -o myls
	gcc mycat.c -o mycat
	gcc myrm.c -o myrm
	gcc mydate.c -o mydate

clear:
	rm mycat
	rm mydate
	rm myls
	rm mymkdir
	rm myrm
	rm shell